// this file is automatically generated by json2cpp.py

#pragma once

constexpr uint8_t NUM_FV1_PROGRAMS = 100;

extern const Program fv1_programs[NUM_FV1_PROGRAMS];

constexpr uint8_t LONGEST_PROGRAM_NAME = 57;
constexpr uint8_t LONGEST_PARAM_NAME = 26;
constexpr uint8_t LONGEST_NAME = 57;
