// this file is automatically generated by json2cpp.py

const char str_Chorus[] PROGMEM = "Chorus";
const char str_Reverb[] PROGMEM = "Reverb";
const char str_Rate[] PROGMEM = "Rate";
const char str_Level[] PROGMEM = "Level";
const char str_Flange[] PROGMEM = "Flange";
const char str_Tremolo[] PROGMEM = "Tremolo";
const char str_Pitch_shift[] PROGMEM = "Pitch shift";
const char str_Pitch[] PROGMEM = "Pitch";
const char str_Pitch_echo[] PROGMEM = "Pitch echo";
const char str_pitch[] PROGMEM = "pitch";
const char str_delay[] PROGMEM = "delay";
const char str_mix[] PROGMEM = "mix";
const char str_Reverb_1[] PROGMEM = "Reverb 1";
const char str_time[] PROGMEM = "time";
const char str_HF_filter[] PROGMEM = "HF filter";
const char str_LF_filter[] PROGMEM = "LF filter";
const char str_Reverb_2[] PROGMEM = "Reverb 2";
const char str_Hall_Reverb_with_Shimmer[] PROGMEM = "Hall Reverb with Shimmer";
const char str_Damping[] PROGMEM = "Damping";
const char str_Feedback[] PROGMEM = "Feedback";
const char str_Decay[] PROGMEM = "Decay";
const char str_Reverb___Shimmer__Version_6_[] PROGMEM = "Reverb + Shimmer (Version 6)";
const char str_Reverb_time[] PROGMEM = "Reverb time";
const char str_Treble[] PROGMEM = "Treble";
const char str_Shimmer[] PROGMEM = "Shimmer";
const char str__unknown_[] PROGMEM = "<unknown>";

const uint8_t bin_shimmer_1_h[0x1cc] PROGMEM = {
#include "FV-1/spn/shimmer-1.h"
};

const uint8_t bin_shimmer_drAlx_h[0x18c] PROGMEM = {
#include "FV-1/spn/shimmer_drAlx.h"
};

const ProgParams param_ff_0800_0400_0400 PROGMEM = { .mix = 0xff, .pots = {0x0800, 0x0400, 0x0400} };
const ProgParams param_80_0800_0800_0800 PROGMEM = { .mix = 0x80, .pots = {0x0800, 0x0800, 0x0800} };
const ProgParams param_40_0800_0800_0800 PROGMEM = { .mix = 0x40, .pots = {0x0800, 0x0800, 0x0800} };

const uint8_t num_fv1_programs = 9;

const Program fv1_programs[9] PROGMEM =
{
// ROM programs
{
.name = str_Chorus,
.pot_names = {str_Reverb, str_Rate, str_Level},
.params = &param_ff_0800_0400_0400,
.binary_length = 0,
.binary = nullptr,
},
{
.name = str_Flange,
.pot_names = {str_Reverb, str_Rate, str_Level},
.params = &param_ff_0800_0400_0400,
.binary_length = 1,
.binary = nullptr,
},
{
.name = str_Tremolo,
.pot_names = {str_Reverb, str_Rate, str_Level},
.params = &param_ff_0800_0400_0400,
.binary_length = 2,
.binary = nullptr,
},
{
.name = str_Pitch_shift,
.pot_names = {str_Pitch, nullptr, nullptr},
.params = &param_ff_0800_0400_0400,
.binary_length = 3,
.binary = nullptr,
},
{
.name = str_Pitch_echo,
.pot_names = {str_pitch, str_delay, str_mix},
.params = &param_ff_0800_0400_0400,
.binary_length = 4,
.binary = nullptr,
},
{
.name = str_Reverb_1,
.pot_names = {str_time, str_HF_filter, str_LF_filter},
.params = &param_80_0800_0800_0800,
.binary_length = 6,
.binary = nullptr,
},
{
.name = str_Reverb_2,
.pot_names = {str_time, str_HF_filter, str_LF_filter},
.params = &param_80_0800_0800_0800,
.binary_length = 7,
.binary = nullptr,
},
// external programs
{
.name = str_Reverb___Shimmer__Version_6_,
.pot_names = {str_Reverb_time, str_Treble, str_Shimmer},
.params = &param_40_0800_0800_0800,
.binary_length = 396,
.binary = bin_shimmer_drAlx_h
},
{
.name = str_Hall_Reverb_with_Shimmer,
.pot_names = {str_Damping, str_Feedback, str_Decay},
.params = &default_params,
.binary_length = 460,
.binary = bin_shimmer_1_h
},
};
