// this file is automatically generated by json2cpp.py

#pragma once

constexpr uint8_t NUM_FV1_PROGRAMS = 9;

extern const Program fv1_programs[NUM_FV1_PROGRAMS];

constexpr uint8_t LONGEST_PROGRAM_NAME = 25;
constexpr uint8_t LONGEST_PARAM_NAME = 12;
constexpr uint8_t LONGEST_NAME = 25;
